name: PAPI Feature Request
description: Request additional functionality or suggest a new approach to existing functionality
title: "[Feature Request]: "
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to make a feature request!
  - type: textarea
    id: feature-request
    attributes:
      label: Description of Feature Request
      description: Describe the feature that you would like to see in PAPI.
    validations:
      required: True
  - type: input
    id: component
    attributes:
      label: Component
      description: If this is for a specific PAPI component, please mention it here (optional). 
      placeholder: e.g. Cuda
    validations:
      required: False
